### ISSUE TITLE
Example fails: can't find karma/bin/karma

### ISSUE THREAD

**Issue by appsforartists** [alexeagle/rules_karma#3]
```
~/Projects/rules_karma ☀ master
❯ bazel test examples/ts

INFO: Found 1 test target...
FAIL: //examples/ts:ts (see /private/var/tmp/_bazel_brentons/30e5393510bb207659359b93305b7f39/execroot/karma/bazel-out/darwin_x86_64-fastbuild/testlogs/examples/ts/ts/test.log).
INFO: From Testing //examples/ts:ts:
==================== Test output for //examples/ts:ts:
failed to load main  Error: Cannot find module 'karma/bin/karma'
  looked in:
   karma/bin/karma,
   undefined,
   undefined
    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_brentons/30e5393510bb207659359b93305b7f39/execroot/karma/bazel-out/darwin_x86_64-fastbuild/bin/external/karma/internal/karma_bin_loader.js:130:15)
    at Function.Module._load (module.js:417:25)
    at Object.<anonymous> (/private/var/tmp/_bazel_brentons/30e5393510bb207659359b93305b7f39/execroot/karma/bazel-out/darwin_x86_64-fastbuild/bin/external/karma/internal/karma_bin_loader.js:142:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
================================================================================
Target //examples/ts:ts up-to-date:
  dist/bin/examples/ts/ts
INFO: Elapsed time: 9.957s, Critical Path: 7.58s
//examples/ts:ts                                                         FAILED in 0.6s
  /private/var/tmp/_bazel_brentons/30e5393510bb207659359b93305b7f39/execroot/karma/bazel-out/darwin_x86_64-fastbuild/testlogs/examples/ts/ts/test.log

Executed 1 out of 1 test: 1 fails locally.
```

**Comment by appsforartists** [comment]
I can't even figure out where karma_bin_loader is coming from.  If I run `bazel clean`, I can't find the source for it.

**Comment by alexeagle** [comment]
probably you don't have `node_modules/karma/bin/karma` in your node_modules `filegroup`

I'll just stop requiring that, it's a one-line file.
